name: Deploy Frontend to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to S3
        run: aws s3 sync dist/ s3://${{ secrets.eventm-bucket }} --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIAQ7IJJJD2RRRBWARU }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aeqLTU+Hq7kJWAz4Y2dIbSvzdkl7zUtUeBve8RcB }}
          AWS_DEFAULT_REGION: ${{ secrets.ap-south-2 }}

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.E3DA4SZYZW0AA2 }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIAQ7IJJJD2RRRBWARU }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aeqLTU+Hq7kJWAz4Y2dIbSvzdkl7zUtUeBve8RcB }}
          AWS_DEFAULT_REGION: ${{ secrets.ap-south-2 }}